# npm install
# pm2 stop default
# pm2 start npm -- start

- name: "update local apt repo."
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: yes

- name: "install dependencies [nodejs and npm]."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Copy artifact into Instance" 
  copy:
    src: tmp/artifact.tar.gz
    dest: /home/ubuntu/

- name: "Copy artifact into Instance" 
  copy:
    src: tmp/backend
    dest: /home/ubuntu/

# - name: Creates directory
#   file:
#     path: ~/dist
#     state: directory

# - name: list file
#   shell: |
#     sudo tar -czvf ~/artifact.tar.gz ~/dist

- name: "Start app"
  become: true
  shell: |
    # cd ~/dist
    cd ~/backend
    npm install
    npm run build
    pm2 stop default
    pm2 start npm -- start
