# npm install
# pm2 stop default
# pm2 start npm -- start

- name: stop pm2
  become: true
  shell: |
    pm2 stop default

- name: "Copy artifact into Instance" 
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: extract artifact to distribution
  shell: |
    tar -czvf ~/artifact.tar.gz ~/dist

- name: change directory
  shell: |
    cd dist

- name: strt pm2 with  npm
  shell: |
    pm2 start npm -- start